apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: octopilot-pipeline-tools
build:
  artifacts:
    - image: octopilot-pipeline-tools
      buildpacks:
        builder: ghcr.io/octopilot/builder-jammy-base:0.1.198
