apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: octopilot-pipeline-tools
build:
  artifacts:
  - image: op-base
    context: base
    docker:
      dockerfile: Dockerfile
  - image: op
    context: .
    buildpacks:
      builder: ghcr.io/octopilot/builder-jammy-base:0.1.198
      runImage: op-base
      env:
        - BP_GO_VERSION=1.25.6
        - GOFLAGS=-buildvcs=false
        - BP_GO_BUILD_FLAGS=-buildvcs=false
