apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: octopilot-pipeline-tools
build:
  artifacts:
  - image: op-base
    context: base
    docker:
      dockerfile: Dockerfile
  - image: op
    context: .
    buildpacks:
      # builder: ghcr.io/octopilot/builder-jammy-base:0.1.198 - this image is too large for the github action runner, resulting in disk space issues
      builder: paketobuildpacks/build-jammy-tiny:0.2.9
      runImage: op-base
      env:
        - GOFLAGS=-buildvcs=false
        - BP_GO_BUILD_FLAGS=-buildvcs=false
        # BP_GO_VERSION is set by the pipeline
